

##########################
# Makefile.in generated by automake 1.10.2 from Makefile.am.
# src/test/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/protobuf-c
pkglibdir = $(libdir)/protobuf-c
pkgincludedir = $(includedir)/protobuf-c
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
check_PROGRAMS = test-generated-code$(EXEEXT) \
	test-generated-code2$(EXEEXT) test-rpc$(EXEEXT)
noinst_PROGRAMS = cxx-generate-packed-data$(EXEEXT) \
	example-server$(EXEEXT) example-client$(EXEEXT)
TESTS = test-generated-code$(EXEEXT) test-generated-code2$(EXEEXT) \
	test-rpc$(EXEEXT)
subdir = src/test
DIST_COMMON = README $(srcdir)/Makefile.am $(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
PROGRAMS = $(noinst_PROGRAMS)
am_cxx_generate_packed_data_OBJECTS =  \
	cxx-generate-packed-data.$(OBJEXT) test-full.pb.$(OBJEXT)
cxx_generate_packed_data_OBJECTS =  \
	$(am_cxx_generate_packed_data_OBJECTS)
cxx_generate_packed_data_DEPENDENCIES =
cxx_generate_packed_data_LINK = $(LIBTOOL) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(cxx_generate_packed_data_LDFLAGS) \
	$(LDFLAGS) -o $@
am_example_client_OBJECTS = example-client.$(OBJEXT) \
	test.pb-c.$(OBJEXT)
example_client_OBJECTS = $(am_example_client_OBJECTS)
example_client_DEPENDENCIES = ../libprotobuf-c.la
am_example_server_OBJECTS = example-server.$(OBJEXT) \
	test.pb-c.$(OBJEXT) iniparser.$(OBJEXT) dictionary.$(OBJEXT)
example_server_OBJECTS = $(am_example_server_OBJECTS)
example_server_DEPENDENCIES = ../libprotobuf-c.la
am_test_generated_code_OBJECTS = test-generated-code.$(OBJEXT) \
	test.pb-c.$(OBJEXT)
test_generated_code_OBJECTS = $(am_test_generated_code_OBJECTS)
test_generated_code_DEPENDENCIES = ../libprotobuf-c.la
am_test_generated_code2_OBJECTS = test-generated-code2.$(OBJEXT) \
	test-full.pb-c.$(OBJEXT)
test_generated_code2_OBJECTS = $(am_test_generated_code2_OBJECTS)
test_generated_code2_DEPENDENCIES = ../libprotobuf-c.la
am_test_rpc_OBJECTS = test-rpc.$(OBJEXT) test.pb-c.$(OBJEXT)
test_rpc_OBJECTS = $(am_test_rpc_OBJECTS)
test_rpc_DEPENDENCIES = ../libprotobuf-c.la
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(cxx_generate_packed_data_SOURCES) \
	$(example_client_SOURCES) $(example_server_SOURCES) \
	$(test_generated_code_SOURCES) $(test_generated_code2_SOURCES) \
	$(test_rpc_SOURCES) \
	$(iniparser_SOURCES) \
	$(dictionary_SOURCES) 
#	inisrc/dectionary.c inisrc/dictionary.h \
#	inisrc/iniparser.c inisrc/iniparser.c
DIST_SOURCES = $(cxx_generate_packed_data_SOURCES) \
	$(example_client_SOURCES) $(example_server_SOURCES) \
	$(test_generated_code_SOURCES) $(test_generated_code2_SOURCES) \
	$(test_rpc_SOURCES) \
	$(iniparser_SOURCES) \
	$(dictionary_SOURCES) 
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /tmp/protobuf-c-0.15/missing --run aclocal-1.10
AMTAR = ${SHELL} /tmp/protobuf-c-0.15/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /tmp/protobuf-c-0.15/missing --run autoconf
AUTOHEADER = ${SHELL} /tmp/protobuf-c-0.15/missing --run autoheader
AUTOMAKE = ${SHELL} /tmp/protobuf-c-0.15/missing --run automake-1.10
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"protobuf-c\" -DPACKAGE_TARNAME=\"protobuf-c\" -DPACKAGE_VERSION=\"0.15\" -DPACKAGE_STRING=\"protobuf-c\ 0.15\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"protobuf-c\" -DVERSION=\"0.15\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_INTTYPES_H=1 -DHAVE_SYS_POLL_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_ALLOCA_H=1 -DHAVE_MALLOC_H=1 -DHAVE_SYS_UIO_H=1 -DHAVE_UNISTD_H=1 -DHAVE_ENDIAN_H=1 -DIS_LITTLE_ENDIAN=1
DEPDIR = .deps
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /tmp/protobuf-c-0.15/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = protobuf-c
PACKAGE_BUGREPORT = 
PACKAGE_NAME = protobuf-c
PACKAGE_STRING = protobuf-c 0.15
PACKAGE_TARNAME = protobuf-c
PACKAGE_VERSION = 0.15
PATH_SEPARATOR = :
PROTOC = /usr/bin/protoc
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 0.15
abs_builddir = /tmp/protobuf-c-0.15/src/test
abs_srcdir = /tmp/protobuf-c-0.15/src/test
abs_top_builddir = /tmp/protobuf-c-0.15
abs_top_srcdir = /tmp/protobuf-c-0.15
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /tmp/protobuf-c-0.15/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../
top_builddir = ../..
top_srcdir = ../..
INCLUDES = -I$(srcdir)/..
test_generated_code_SOURCES = \
test-generated-code.c \
generated-code/test.pb-c.c

test_generated_code_LDADD = \
../libprotobuf-c.la

test_generated_code2_SOURCES = \
test-generated-code2.c \
generated-code/test-full.pb-c.c

test_generated_code2_LDADD = \
../libprotobuf-c.la

test_rpc_SOURCES = \
test-rpc.c \
generated-code/test.pb-c.c

iniparser_SOURCES = \
inisrc/iniparser.c \
inisrc/dictionary.c

dictionary_SOURCES = \
inisrc/dictionary.c

test_rpc_LDADD = \
../libprotobuf-c.la

cxx_generate_packed_data_SOURCES = \
cxx-generate-packed-data.cc generated-code/test-full.pb.cc

cxx_generate_packed_data_LDADD = -lprotobuf
cxx_generate_packed_data_LDFLAGS = -pthread
example_server_SOURCES = \
example-server.c generated-code/test.pb-c.c \
inisrc/iniparser.c inisrc/dictionary.c

example_server_LDADD = ../libprotobuf-c.la
example_client_SOURCES = \
example-client.c generated-code/test.pb-c.c

example_client_LDADD = ../libprotobuf-c.la
BUILT_SOURCES = generated-code/test.pb-c.c generated-code/test.pb-c.h \
                generated-code/test-full.pb-c.c generated-code/test-full.pb-c.h \
                generated-code/test-full.pb.cc generated-code/test-full.pb.h \
                generated-code/test-full-cxx-output.inc \
				inisrc/dictionary.c  inisrc/dictionary.h \
				inisrc/iniparser.c inisrc/iniparser.h

DISTCLEANFILES = $(BUILT_SOURCES)
EXTRA_DIST = test.proto test-full.proto common-test-arrays.h
all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cc .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  src/test/Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  src/test/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

clean-checkPROGRAMS:
	@list='$(check_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done

clean-noinstPROGRAMS:
	@list='$(noinst_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
cxx-generate-packed-data$(EXEEXT): $(cxx_generate_packed_data_OBJECTS) $(cxx_generate_packed_data_DEPENDENCIES) 
	@rm -f cxx-generate-packed-data$(EXEEXT)
	$(cxx_generate_packed_data_LINK) $(cxx_generate_packed_data_OBJECTS) $(cxx_generate_packed_data_LDADD) $(LIBS)
example-client$(EXEEXT): $(example_client_OBJECTS) $(example_client_DEPENDENCIES) 
	@rm -f example-client$(EXEEXT)
	$(LINK) $(example_client_OBJECTS) $(example_client_LDADD) $(LIBS)
example-server$(EXEEXT): $(example_server_OBJECTS) $(example_server_DEPENDENCIES) 
	@rm -f example-server$(EXEEXT)
	$(LINK) $(example_server_OBJECTS) $(example_server_LDADD) $(LIBS)
test-generated-code$(EXEEXT): $(test_generated_code_OBJECTS) $(test_generated_code_DEPENDENCIES) 
	@rm -f test-generated-code$(EXEEXT)
	$(LINK) $(test_generated_code_OBJECTS) $(test_generated_code_LDADD) $(LIBS)
test-generated-code2$(EXEEXT): $(test_generated_code2_OBJECTS) $(test_generated_code2_DEPENDENCIES) 
	@rm -f test-generated-code2$(EXEEXT)
	$(LINK) $(test_generated_code2_OBJECTS) $(test_generated_code2_LDADD) $(LIBS)
test-rpc$(EXEEXT): $(test_rpc_OBJECTS) $(test_rpc_DEPENDENCIES) 
	@rm -f test-rpc$(EXEEXT)
	$(LINK) $(test_rpc_OBJECTS) $(test_rpc_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/cxx-generate-packed-data.Po
include ./$(DEPDIR)/example-client.Po
include ./$(DEPDIR)/example-server.Po
include ./$(DEPDIR)/test-full.pb-c.Po
include ./$(DEPDIR)/test-full.pb.Po
include ./$(DEPDIR)/test-generated-code.Po
include ./$(DEPDIR)/test-generated-code2.Po
include ./$(DEPDIR)/test-rpc.Po
include ./$(DEPDIR)/test.pb-c.Po
#include ./$(DEPDIR)/iniparser.Po
#include ./$(DEFDIR)/dictionary.Po
.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

test.pb-c.o: generated-code/test.pb-c.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT test.pb-c.o -MD -MP -MF $(DEPDIR)/test.pb-c.Tpo -c -o test.pb-c.o `test -f 'generated-code/test.pb-c.c' || echo '$(srcdir)/'`generated-code/test.pb-c.c
	mv -f $(DEPDIR)/test.pb-c.Tpo $(DEPDIR)/test.pb-c.Po
#	source='generated-code/test.pb-c.c' object='test.pb-c.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o test.pb-c.o `test -f 'generated-code/test.pb-c.c' || echo '$(srcdir)/'`generated-code/test.pb-c.c
dictionary.o: inisrc/dictionary.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT dictionary.o -MD -MP -MF $(DEPDIR)/dictionary.Tpo -c -o dictionary.o `test -f 'inisrc/dictionary.c' || echo '$(srcdir)/'`inisrc/dictionary.c
	mv -f $(DEPDIR)/dictionary.Tpo $(DEPDIR)/dictionary.Po


iniparser.o: inisrc/iniparser.c	dictionary.o 
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT iniparser.o -MD -MP -MF $(DEPDIR)/iniparser.Tpo -c -o iniparser.o `test -f 'inisrc/iniparser.c' || echo '$(srcdir)/'`inisrc/iniparser.c
	mv -f $(DEPDIR)/dictionary.Tpo $(DEPDIR)/dictionary.Po


test.pb-c.obj: generated-code/test.pb-c.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT test.pb-c.obj -MD -MP -MF $(DEPDIR)/test.pb-c.Tpo -c -o test.pb-c.obj `if test -f 'generated-code/test.pb-c.c'; then $(CYGPATH_W) 'generated-code/test.pb-c.c'; else $(CYGPATH_W) '$(srcdir)/generated-code/test.pb-c.c'; fi`
	mv -f $(DEPDIR)/test.pb-c.Tpo $(DEPDIR)/test.pb-c.Po
#	source='generated-code/test.pb-c.c' object='test.pb-c.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o test.pb-c.obj `if test -f 'generated-code/test.pb-c.c'; then $(CYGPATH_W) 'generated-code/test.pb-c.c'; else $(CYGPATH_W) '$(srcdir)/generated-code/test.pb-c.c'; fi`

test-full.pb-c.o: generated-code/test-full.pb-c.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT test-full.pb-c.o -MD -MP -MF $(DEPDIR)/test-full.pb-c.Tpo -c -o test-full.pb-c.o `test -f 'generated-code/test-full.pb-c.c' || echo '$(srcdir)/'`generated-code/test-full.pb-c.c
	mv -f $(DEPDIR)/test-full.pb-c.Tpo $(DEPDIR)/test-full.pb-c.Po
#	source='generated-code/test-full.pb-c.c' object='test-full.pb-c.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o test-full.pb-c.o `test -f 'generated-code/test-full.pb-c.c' || echo '$(srcdir)/'`generated-code/test-full.pb-c.c

test-full.pb-c.obj: generated-code/test-full.pb-c.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT test-full.pb-c.obj -MD -MP -MF $(DEPDIR)/test-full.pb-c.Tpo -c -o test-full.pb-c.obj `if test -f 'generated-code/test-full.pb-c.c'; then $(CYGPATH_W) 'generated-code/test-full.pb-c.c'; else $(CYGPATH_W) '$(srcdir)/generated-code/test-full.pb-c.c'; fi`
	mv -f $(DEPDIR)/test-full.pb-c.Tpo $(DEPDIR)/test-full.pb-c.Po
#	source='generated-code/test-full.pb-c.c' object='test-full.pb-c.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o test-full.pb-c.obj `if test -f 'generated-code/test-full.pb-c.c'; then $(CYGPATH_W) 'generated-code/test-full.pb-c.c'; else $(CYGPATH_W) '$(srcdir)/generated-code/test-full.pb-c.c'; fi`

#dictionary.o: inisrc/dictionary.c
#	gcc -o dictionary.o inisrc/dictionary.c

#iniparser.o:inisrc/iniparser.c dictionary.o
#	gcc -o iniparser.o inisrc/iniparser.c
#example-server:iniparser.o
#example-server.$(OBJEXT): iniparser.$(OBJEXT)
#iniparser.$(OBJEXT): dictionary.$(OBJEXT) inisrc/iniparser.c
#	$(CC) $(CFLAGS)  -MT iniparser.o  -MD -MP -MF $(DEPDIR)/iniparser.Po  -o iniparser.o  inisrc/iniparser.c inisrc/iniparser.h 
#dictionary.$(OBJEXT): inisrc/dictionary.c
#	$(CC) $(CFLAGS)  -MT  dictionary.o -MD -MP -MF $(DEPDIR)/dictionary.Po  -o dictionary.o  inisrc/dictionary.c inisrc/dictionary.h 

.cc.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

test-full.pb.o: generated-code/test-full.pb.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test-full.pb.o -MD -MP -MF $(DEPDIR)/test-full.pb.Tpo -c -o test-full.pb.o `test -f 'generated-code/test-full.pb.cc' || echo '$(srcdir)/'`generated-code/test-full.pb.cc
	mv -f $(DEPDIR)/test-full.pb.Tpo $(DEPDIR)/test-full.pb.Po
#	source='generated-code/test-full.pb.cc' object='test-full.pb.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test-full.pb.o `test -f 'generated-code/test-full.pb.cc' || echo '$(srcdir)/'`generated-code/test-full.pb.cc

test-full.pb.obj: generated-code/test-full.pb.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test-full.pb.obj -MD -MP -MF $(DEPDIR)/test-full.pb.Tpo -c -o test-full.pb.obj `if test -f 'generated-code/test-full.pb.cc'; then $(CYGPATH_W) 'generated-code/test-full.pb.cc'; else $(CYGPATH_W) '$(srcdir)/generated-code/test-full.pb.cc'; fi`
	mv -f $(DEPDIR)/test-full.pb.Tpo $(DEPDIR)/test-full.pb.Po
#	source='generated-code/test-full.pb.cc' object='test-full.pb.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test-full.pb.obj `if test -f 'generated-code/test-full.pb.cc'; then $(CYGPATH_W) 'generated-code/test-full.pb.cc'; else $(CYGPATH_W) '$(srcdir)/generated-code/test-full.pb.cc'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
	srcdir=$(srcdir); export srcdir; \
	list=' $(TESTS) '; \
	if test -n "$$list"; then \
	  for tst in $$list; do \
	    if test -f ./$$tst; then dir=./; \
	    elif test -f $$tst; then dir=; \
	    else dir="$(srcdir)/"; fi; \
	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *[\ \	]$$tst[\ \	]*) \
		xpass=`expr $$xpass + 1`; \
		failed=`expr $$failed + 1`; \
		echo "XPASS: $$tst"; \
	      ;; \
	      *) \
		echo "PASS: $$tst"; \
	      ;; \
	      esac; \
	    elif test $$? -ne 77; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *[\ \	]$$tst[\ \	]*) \
		xfail=`expr $$xfail + 1`; \
		echo "XFAIL: $$tst"; \
	      ;; \
	      *) \
		failed=`expr $$failed + 1`; \
		echo "FAIL: $$tst"; \
	      ;; \
	      esac; \
	    else \
	      skip=`expr $$skip + 1`; \
	      echo "SKIP: $$tst"; \
	    fi; \
	  done; \
	  if test "$$all" -eq 1; then \
	    tests="test"; \
	    All=""; \
	  else \
	    tests="tests"; \
	    All="All "; \
	  fi; \
	  if test "$$failed" -eq 0; then \
	    if test "$$xfail" -eq 0; then \
	      banner="$$All$$all $$tests passed"; \
	    else \
	      if test "$$xfail" -eq 1; then failures=failure; else failures=failures; fi; \
	      banner="$$All$$all $$tests behaved as expected ($$xfail expected $$failures)"; \
	    fi; \
	  else \
	    if test "$$xpass" -eq 0; then \
	      banner="$$failed of $$all $$tests failed"; \
	    else \
	      if test "$$xpass" -eq 1; then passes=pass; else passes=passes; fi; \
	      banner="$$failed of $$all $$tests did not behave as expected ($$xpass unexpected $$passes)"; \
	    fi; \
	  fi; \
	  dashes="$$banner"; \
	  skipped=""; \
	  if test "$$skip" -ne 0; then \
	    if test "$$skip" -eq 1; then \
	      skipped="($$skip test was not run)"; \
	    else \
	      skipped="($$skip tests were not run)"; \
	    fi; \
	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$skipped"; \
	  fi; \
	  report=""; \
	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
	    report="Please report to $(PACKAGE_BUGREPORT)"; \
	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$report"; \
	  fi; \
	  dashes=`echo "$$dashes" | sed s/./=/g`; \
	  echo "$$dashes"; \
	  echo "$$banner"; \
	  test -z "$$skipped" || echo "$$skipped"; \
	  test -z "$$report" || echo "$$report"; \
	  echo "$$dashes"; \
	  test "$$failed" -eq 0; \
	else :; fi

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(PROGRAMS)
installdirs:
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-checkPROGRAMS clean-generic clean-libtool \
	clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-exec-am:

install-html: install-html-am

install-info: install-info-am

install-man:

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am:

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-TESTS check-am clean \
	clean-checkPROGRAMS clean-generic clean-libtool \
	clean-noinstPROGRAMS ctags distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am

cxx-generate-packed-data.$(OBJEXT): generated-code/test-full.pb.h

generated-code/test.pb-c.c generated-code/test.pb-c.h: ../protoc-c$(EXEEXT) $(srcdir)/test.proto
	mkdir -p generated-code
	../protoc-c -I$(srcdir) --c_out=generated-code $(srcdir)/test.proto
generated-code/test-full.pb-c.c generated-code/test-full.pb-c.h: ../protoc-c $(srcdir)/test-full.proto
	mkdir -p generated-code
	../protoc-c -I$(srcdir) --c_out=generated-code $(srcdir)/test-full.proto
generated-code/test-full.pb.cc generated-code/test-full.pb.h: $(srcdir)/test-full.proto /usr/bin/protoc
	mkdir -p generated-code
	/usr/bin/protoc -I$(srcdir) --cpp_out=generated-code $(srcdir)/test-full.proto
generated-code/test-full-cxx-output.inc: cxx-generate-packed-data$(EXEEXT)
	./cxx-generate-packed-data > generated-code/test-full-cxx-output.inc
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
